[package]
name = "Transle"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = "0.16.0"
teloxide-core = "0.12.0"
reqwest = "0.12.21"
tokio = {version = "1.45.1",features = ["macros"]}
serde_json = "1.0.140"
serde = "1.0.219"
config = "0.15.11"